name: Python tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ['3.8']
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' #${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install ".[check,test,doc]"
#      - name: Syntax check with black
#        run: black --check cellsium
#      - name: Syntax check with isort
#        run: isort --check cellsium
#      - name: Syntax check with pflake8
#        run: pflake8 cellsium
      - name: unittests with pytest
        run: pytest
      - uses: codecov/codecov-action@v2
